### ISSUE TITLE
Use company identifiers in LL_VERSION_IND

### ISSUE THREAD

**Issue by chocol4te** [jonas-schievink/rubble#38]
Currently a `Hex<u16>` is used to represent `CompId`, this should be an enum of company identifiers which implements `.as_u16()`.

The full list can be found here:
https://www.bluetooth.com/specifications/assigned-numbers/company-identifiers

**Comment by jonas-schievink** [comment]
Alternatively it could also be a `struct CompanyId(u16);` with associated constants for the companies. I'm not sure which is better yet (the enum would need an additional `Unknown` variant carrying the raw `u16`, and also a `#[doc(hidden)]` variant for extensibility since `#[non_exhaustive]` is not yet stable).

In any case it should also get a `.name()` function that returns the exact company identifier from the bluetooth.com list above.

A `fmt::Display` implementation would also be neat.

**Comment by chocol4te** [comment]
Started work on #44

**Comment by jonas-schievink** [comment]
You can put "Closes #38" in your PR description and it'll close this issue automatically when merged, no need to do it before the fix is actually merged.

**Comment by chocol4te** [comment]
Ah sorry, TIL
